### ISSUE TITLE
identifier "KEYPAD_STREAM" is undefined

### ISSUE THREAD

**Issue by CHTUZKI** [terjeio/GRBL_MPG_DRO_BoosterPack#10]
`#define MPG_ENABLE          1    

 #define KEYPAD_ENABLE      2`

I used the above two lines of code to compile, and the compiler told me "identifier" KEYPAD_STREAM "is undefined". I can't find "KEYPAD_STREAM" in the "MSP432P401R-master" project

I don't know why?

**Comment by terjeio** [comment]
Those two symbols are for the grblHAL controller, which driver are you compiling for that?
