### ISSUE TITLE
"GRBL_MPG_DRO_BoosterPack" project compilation error

### ISSUE THREAD

**Issue by CHTUZKI** [terjeio/GRBL_MPG_DRO_BoosterPack#13]
I download the project from this link。`https://github.com/terjeio/GRBL_MPG_DRO_BoosterPack.git`

I use "Code Composer Studio 12.0.0" to open the `GRBL_MPG_DRO_BoosterPack-master\Firmware\TM4C123` project。I compile and the compiler tells me there are 16 errors。
`"../src/canvas/sdcard.c", line 177: error #256: type name is not allowed`
`"../src/canvas/sdcard.c", line 177: error #66: expected a ";"`
`"../src/canvas/sdcard.c", line 177: error #20: identifier "i" is undefined`
`3 errors detected in the compilation of "../src/canvas/sdcard.c".`
`gmake: *** [src/canvas/sdcard.obj] Error 1`

I made a modification to the code：

`if(!canvasSDCard) `
`{`
`       canvasSDCard = UILibCanvasCreate(0, 0, 320, 240, handlerCanvas);`
`		listPrograms = UILibListCreate((Widget *)canvasSDCard, 10, 40, 300, LISTELEMENTS, handlerProgramList);`
`		{`
`		uint_fast8_t i;`
`		for(i = 0; i < LISTELEMENTS; i++)`
`			UILibListCreateElement(listPrograms, i, "", handlerSelectList);`
`		}`
`}`

error disappears。

After I solved all the errors of this type, a new error appeared

`"./src/canvas/grblutils.obj" "./src/canvas/menu.obj" "./src/canvas/sdcard.obj" "./src/canvas/sender.obj"` `"./src/canvas/threading.obj" "./src/fonts.obj" "./src/grblcomm.obj" "./src/interface.obj" "./src/keypad.obj" "./src/main.obj"` `"../tm4c123gh6pm.cmd"  -llibc.a -l"C:/ti/TivaWare_C_Series-2.2.0.295/driverlib/ccs/Debug/driverlib.lib" `
`<Linking>`
 
 `undefined       first referenced  `
`  symbol                  in file       `
` ---------       ----------------  `
` serial_RxCancel ./src/grblcomm.obj`

`error #10234-D: unresolved symbols remain`
`error #10010: errors encountered during linking; "GRBL MPG and DRO Panel.out" not built`
 
`>> Compilation failure`
`makefile:181: recipe for target 'GRBL MPG and DRO Panel.out' failed`
`gmake: *** [GRBL MPG and DRO Panel.out] Error 1`
`gmake: Target 'all' not remade because of errors.`

`**** Build Finished ****`

**Comment by CHTUZKI** [comment]
I made a modification to the code：
`__attribute__((weak)) void serial_RxCancel (void){};`

**Comment by terjeio** [comment]
Retested with Tiva C after RP2040 (Pi Pico) changes, seems ok now.
