### ISSUE TITLE
digression

### ISSUE THREAD

**Issue by CHTUZKI** [terjeio/GRBL_MPG_DRO_BoosterPack#14]
Sorry to take up some of your time.

I see whole project code that is event driven, like the "Display drivers" repository.
I also want to write code in an event-driven way, is there any learning material you can recommend? Or learn the route.😁😁

Thanks~

**Comment by terjeio** [comment]
There are plenty of learning material available if you google for it - I learned how to do it long ago, before much learning material was available.
