### ISSUE TITLE
Can the "GRBL_MPG_DRO_BoosterPack" project set the parameters of GrblHAL

### ISSUE THREAD

**Issue by CHTUZKI** [terjeio/GRBL_MPG_DRO_BoosterPack#17]
I see that grblHAL has many parameters and options. Can "GRBL_MPG_DRO" set grblHAL like iosender?

![image](https://user-images.githubusercontent.com/42321222/221627094-b7ac977a-966c-4c69-9ef4-15c364a7955a.png)

**Comment by terjeio** [comment]
> Can "GRBL_MPG_DRO" set grblHAL like iosender?

No, not without a lot of work - canvases has to be added for editing the settings.

**Comment by CHTUZKI** [comment]
If I add "Edit Settings Canvas" in the "GRBL_MPG_DRO" project

In order to meet the above requirements, does the grblHAL code need to be changed?

**Comment by terjeio** [comment]
> In order to meet the above requirements, does the grblHAL code need to be changed?

No - when in MPG mode you have access to everything that a sender has.

**Comment by CHTUZKI** [comment]
Thank you for your reply。
